# Branch Protection Rules Configuration
# This file defines the protection rules for main branch (production)

branches:
  main:
    protection_rules:
      required_status_checks:
        strict: true
        contexts:
          - "Backend PR Checks"
          - "Frontend PR Checks"
          - "PR Summary"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
      restrictions:
        users: []  # Add specific users if needed
        teams: []  # Add specific teams if needed
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      required_conversation_resolution: true 