name: Branch Cleanup

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  cleanup-branches:
    name: Cleanup Merged Branches
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Delete merged branch
      run: |
            # Only delete feature branches, not main
    if [[ "${{ github.event.pull_request.head.ref }}" != "main" ]]; then
          echo "Deleting merged branch: ${{ github.event.pull_request.head.ref }}"
          git push origin --delete ${{ github.event.pull_request.head.ref }}
        else
          echo "Skipping deletion of protected branch: ${{ github.event.pull_request.head.ref }}"
        fi
        
    - name: Cleanup stale branches
      run: |
        # Get list of remote branches
        git fetch --prune
        
            # List all remote branches except main
    for branch in $(git branch -r | grep -v "origin/main" | grep -v "HEAD" | sed 's/origin\///'); do
          # Check if branch has been merged
          if git branch -r --merged origin/main | grep -q "origin/$branch"; then
            echo "Deleting stale merged branch: $branch"
            git push origin --delete $branch || echo "Failed to delete $branch (may not exist or be protected)"
          fi
        done 