name: CI - Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Configure Poetry
      working-directory: ./backend
      run: |
        echo "⚙️ Configuring Poetry..."
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.prefer-active-python false
        
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: backend/.venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        
    - name: Clear corrupted venv if needed
      working-directory: ./backend
      run: |
        if [ -d ".venv" ] && [ ! -f ".venv/bin/python" ]; then
          echo "⚠️ Corrupted virtual environment detected, removing..."
          rm -rf .venv
        fi
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        echo "📦 Installing backend dependencies..."
        # Always install dependencies to ensure dev tools are available
        poetry install --no-interaction --no-root --with dev
        
        # Verify critical dev dependencies are available
        echo "🔍 Verifying critical dependencies..."
        if ! poetry run flake8 --version > /dev/null 2>&1; then
          echo "❌ flake8 not found, attempting fallback installation..."
          poetry add --group dev flake8
        fi
        
        if ! poetry run bandit --version > /dev/null 2>&1; then
          echo "❌ bandit not found, attempting fallback installation..."
          poetry add --group dev bandit
        fi
        
        if ! poetry run safety --version > /dev/null 2>&1; then
          echo "❌ safety not found, attempting fallback installation..."
          poetry add --group dev safety
        fi
        
        if ! poetry run pytest --version > /dev/null 2>&1; then
          echo "❌ pytest not found, attempting fallback installation..."
          poetry add --group dev pytest pytest-cov
        fi
        
        echo "✅ Dependencies installation completed"
        
    - name: Verify dev dependencies
      working-directory: ./backend
      run: |
        echo "🔍 Verifying dev dependencies are installed..."
        poetry run flake8 --version || echo "❌ flake8 not found"
        poetry run bandit --version || echo "❌ bandit not found"
        poetry run safety --version || echo "❌ safety not found"
        poetry run pytest --version || echo "❌ pytest not found"
        
    - name: Run linting
      working-directory: ./backend
      run: |
        echo "🔍 Running backend linting..."
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run security scan
      working-directory: ./backend
      run: |
        poetry run bandit -r . -f json -o bandit-report.json || true
        poetry run safety check --json --output safety-report.json || true
        
    - name: Run tests
      working-directory: ./backend
      run: poetry run pytest tests/ -v --cov=. --cov-report=xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage

  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Run type checking
      working-directory: ./frontend
      run: npx tsc --noEmit
      
    - name: Run security audit
      working-directory: ./frontend
      run: npm audit --audit-level=moderate
      
    - name: Build application
      working-directory: ./frontend
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/.next
        retention-days: 1 