name: Development Tests

on:
  push:
    branches: [ dev ]

concurrency:
  group: development
  cancel-in-progress: false

jobs:
  test-backend-dev:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install dependencies
      working-directory: ./backend
      run: poetry install --no-interaction --no-root
      
    - name: Run tests
      working-directory: ./backend
      run: poetry run pytest tests/ -v
      
    - name: Run linting
      working-directory: ./backend
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-frontend-dev:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Run type checking
      working-directory: ./frontend
      run: npx tsc --noEmit
      
    - name: Build application
      working-directory: ./frontend
      run: npm run build
      
    - name: Notify test completion
      if: success()
      run: |
        echo "✅ Development tests completed successfully!"
        echo "📝 Note: No deployment to development environment (requires paid plan)"
        echo "🚀 Production deployment will be available when merging to main" 